name: asif
on: 
  push
jobs:
  job1:
    name: abcd
    runs-on: [self-hosted,production,Linux]
    steps:
    - name: step1
      run: echo "my name is asif"
    - uses: cschleiden/replace-tokens@vl
